/* ORDERSALES TABLOSU UZERÝNDE HANGI SEHIRDE NE KADARLIK SATIS YAPILDIGI
BILGISINI CEKEN SORGU */

SELECT CITY,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS
GROUP BY CITY
ORDER BY CITY  


/* SALEORDERS TABLOSU SEHIRLERE GORE HANGI AYDA NE KADARLIK SATIS YAPILDIGI
BILGISINI GETIREN SORGU */

SELECT CITY,MONTH_,SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS
GROUP BY CITY,MONTH_
ORDER BY CITY,MONTH_  

/* HER ILIN HAFTANIN EN COK HANGI GUNUNDE SATIS YAPTIGINI OGRENIP ONA GORE SEHIR VE 
GUNLERE OZEL KAMPANYA YAPMAK ISTIYORUZ. SEHIRLERIN HAFTANIN GUNLERINE GORE NE KADARLIK SATIS
YAPTIGINI GETIREN SORGU */

SELECT CITY,DAYOFWEEK_ ,SUM(LINETOTAL) AS TOTALSALE
FROM SALEORDERS
GROUP BY CITY,DAYOFWEEK_
ORDER BY CITY,DAYOFWEEK_  

/* HER ILIN HAFTANIN EN COK HANGI GUNUNDE SATIS YAPTIGINI OGRENIP ONA GORE
SEHIR VE GUNLERE OZEL KAMPANYA YAPMAK ISTIYORUZ. SEHIRLERIN HAFTANIN GUNLERINE GORE NE KADARLIK SATIS YAPTIGI
BILGISINI GETIREN SORGU */

SELECT 
DISTINCT CITY, 
(SELECT SUM(LINETOTAL) FROM  SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '01.PZT') AS PAZARTESI, 
(SELECT SUM(LINETOTAL) FROM  SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '02.SAL') AS SALI, 
(SELECT SUM(LINETOTAL) FROM  SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '03.ÇAR') AS CARSAMBA, 
(SELECT SUM(LINETOTAL) FROM  SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '04.PER') AS PERSEMBE, 
(SELECT SUM(LINETOTAL) FROM  SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '05.CUM') AS CUMA, 
(SELECT SUM(LINETOTAL) FROM  SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '06.CMT') AS CUMARTESI, 
(SELECT SUM(LINETOTAL) FROM  SALEORDERS WHERE CITY = S.CITY AND DAYOFWEEK_ = '07.PAZ') AS PAZAR

FROM SALEORDERS S
ORDER BY CITY  


/* HER ILIN EN COK SATAN ILK 5 KATEGORISINI GETIREN SORGU */ 

SELECT
S.CITY, S1.CATEGORY1,SUM(S1.TOTALSALE) AS TOTALSALE
FROM SALEORDERS S
CROSS APPLY (SELECT TOP 5 CATEGORY1,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY = S.CITY GROUP BY CATEGORY1 ORDER BY TOTALSALE DESC) S1
GROUP BY S.CITY,S1.CATEGORY1
ORDER BY S.CITY,SUM(S1.TOTALSALE) DESC  


/* ILISKISEL TABLOLARI KULLANARAK HANGI SEHIRDE NE KADARLIK SATIS YAPILDIGI BILGISI */

SELECT CT.CITY,SUM(O.TOTALPRICE) AS TOTALPRICE
FROM ORDERS O
INNER JOIN ADDRESS ADR ON ADR.ID = O .ADDRESSID
INNER JOIN CITIES CT ON CT.ID = ADR.CITYID
GROUP BY CT.CITY 

/* HER MARKANIN ANA KATEGORIYE GORE EN COK SATAN CATEGORY1 ALANINI GETIREN SORGU */

SELECT 
ITM.BRAND, ITM.CATEGORY1,SUM(OD.LINETOTAL) AS TOTALPRICE
FROM
ORDERDETAILS OD
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY ITM.BRAND,ITM.CATEGORY1
ORDER BY BRAND  

/* HER KATEGORININ ICERISINDE EN COK SATAN MARKAYI GETIREN SORGU */

SELECT 
ITM.CATEGORY1,ITM.BRAND,SUM(OD.LINETOTAL) AS TOTALPRICE
FROM
ORDERDETAILS OD
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
GROUP BY ITM.CATEGORY1,ITM.BRAND
ORDER BY ITM.CATEGORY1,SUM(OD.LINETOTAL) DESC 


/* HER BIR URUN ZAMAN ICINDE FARAKLI FIYATLAR ILE SATILMAKTADIR. HER URUNUN
MINIMUM, MAXIMUM VE ORTALAMA NE KADAR FIYATTAN SATILDIGI BILGISI ILE
KAC KEC VE KAC ADET SATILDIGI BILGISINI GETIREN SORGU */

SELECT
ITM.BRAND, ITM.CATEGORY1, ITM.ITEMCODE, ITM.ITEMNAME,
COUNT(OD.ID) AS SALECOUNT, SUM(OD.AMOUNT) AS TOTALAMOUNT,
MIN(OD.UNITPRICE) AS MINPRICE, MAX(OD.UNITPRICE) AS MAXPRICE,
AVG(OD.UNITPRICE) AS AVGPRICE
FROM ITEMS ITM
INNER JOIN ORDERDETAILS OD ON OD.ITEMID = ITM.ID
GROUP BY ITM.BRAND, ITM.CATEGORY1, ITM.ITEMCODE, ITM.ITEMNAME  

/* MUSTERILERIN SISTEMDE KAYITLI ADRES SAYISINI VE SON ALISVERIS YAPTIGI ADRES BILGISINI GETIR */

SELECT U.ID, U.NAMESURNAME,
(SELECT COUNT(*) FROM ADDRESS WHERE USERID=U.ID) AS ADRESSCOUNT,
(SELECT ADDRESSTEXT FROM ADDRESS WHERE ID IN
				(SELECT TOP 1 ADDRESSID FROM ORDERS WHERE USERID = U.ID ORDER BY DATE_ DESC)
) LASTSHOPPINGADRESS
FROM USERS U 



