/* SIREKTIMIZDE HALA CALISMAYA DEVAM EDEN CALISANLARIN 
LISTESINI GETIREN SORGU */

SELECT * FROM PERSON
WHERE OUTDATE IS NOT NULL  

/* SIRKETTE DEPARTMAN BAZLI HALA CALISMAYA DEVAM EDEN 
KADIN VE ERKEK SAYILARINI GETIR */

SELECT 
D.DEPARTMENT,
CASE
	WHEN P.GENDER='E' THEN 'Erkek'
	ELSE 'Kadýn'
END AS GENDER,
COUNT(P.ID) AS PERSONCOUNT
FROM PERSON P
INNER JOIN DEPARTMENT D ON D.ID = P.DEPARTMENTID
WHERE P.OUTDATE IS NULL
GROUP BY D.DEPARTMENT, P.GENDER
ORDER BY D.DEPARTMENT, GENDER 

/* SIRKETTE DEPARTMAN BAZLI HALA CALISMAYA DEVAM EDEN KADIN VE ERKEK
SAYILARINI SEKILDEKI GIBI GETIREN SORGU */

SELECT DEPARTMENT,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND GENDER ='E' AND OUTDATE IS NULL) AS MALE_PERSONCOUNT,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND GENDER ='K' AND OUTDATE IS NULL) AS FEMALE_PERSONCOUNT,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND OUTDATE IS NULL) AS TOTAL_PERSONCOUNT
FROM
DEPARTMENT D
ORDER BY D.DEPARTMENT 

/* PLANLAMA DEPARTMANINA YENI BIR SEF ATAMASI YAPILDI
VE MAASINI BELIRLEMEK ISTIYORUZ. PLANLAMA DEPARTMANI IÇIN
MIN, MAX, MEAN SEF MAASI GETÝREN SORGU (ISTEN CIKMIS PERSONEL MAASLARIDA DAHILDIR) */

/* SUBQUERY ILE 

SELECT
POS.POSITION,
(SELECT MIN(SALARY) FROM PERSON WHERE POSITIONID = POS.ID) AS MIN_SALARY,
(SELECT MAX(SALARY) FROM PERSON WHERE POSITIONID = POS.ID) AS MAX_SALARY,
(SELECT ROUND(AVG(SALARY),0) FROM PERSON WHERE POSITIONID = POS.ID) AS AVG_SALARY
FROM POSITION POS
WHERE POS.POSITION = 'PLANLAMA ÞEFÝ' */

SELECT 
POS.POSITION,MIN(P.SALARY) AS MIN_SALARY,
MAX(P.SALARY) AS MAX_SALARY,
ROUND(AVG(P.SALARY),0) AS AVG_SALARY
FROM POSITION POS
INNER JOIN PERSON P ON P.POSITIONID = POS.ID
WHERE POS.POSITION = 'PLANLAMA ÞEFÝ'
GROUP BY POS.POSITION  

/* HERBIR POZISYONDA MEVCUT HALDE CALISANLAR OLARAK KAC KISI VE ORTALAMA MAASLARININ 
NE KADAR OLDUGUNU LISTELETTIRMEK ISTIYORUZ. BU SOUNUC GETIREN SORGU */

SELECT  
POS.POSITION,COUNT(P.ID) AS PERSONCOUNT,
ROUND(AVG(P.SALARY),0) AS AVG_SALARY
FROM POSITION POS
INNER JOIN PERSON P ON P.POSITIONID = POS.ID
GROUP BY POS.POSITION
ORDER BY POS.POSITION   
 
/* YILLARA GORE ISE ALINAN PERSONEL SAYISINI KADIN VE ERKEK BAZINDA
LISTELETTIREN SORGU */

SELECT DISTINCT YEAR(INDATE) YEAR_,
(SELECT COUNT(*) FROM PERSON WHERE GENDER = 'E' AND YEAR(INDATE) = YEAR(P.INDATE)) AS MALE_PERSONCOUNT,
(SELECT COUNT(*) FROM PERSON WHERE GENDER = 'K' AND YEAR(INDATE) = YEAR(P.INDATE)) AS FEMALE_PERSONCOUNT
FROM PERSON P
ORDER BY YEAR_ 

/* HERBIR PERSONELIMIZIN NE KADAR ZAMANDIR CALISTIGI BILGISINI 
AY OLARAK GETIREN SORGU */

SELECT NAME_+ ' '+SURNAME AS PERSON,
INDATE,OUTDATE,
CASE
	WHEN OUTDATE IS NOT NULL THEN 'ÝÞTEN AYRILDI'
	ELSE 'DEVAM EDÝYOR'
END AS WORKINGSTATUS,

GETDATE(),
CASE 
	WHEN OUTDATE IS NOT NULL THEN DATEDIFF(MONTH,INDATE,OUTDATE)
	ELSE DATEDIFF(MONTH,INDATE,GETDATE())
END AS WORKINGTIME
FROM PERSON  

/* SIRKET 5.YILINDA USTUNDE HERKESIN ISMININ VE SOYISIMININ BAS HARFLERININ BULUNDUGU ,
BIR AJANDA BASTIRIP CALISANLARINA HEDIYE EDECEKTIR. BUNUN ICIN HANGI HARF KOMBINASYONUNDAN
EN AZ NE KADAR SAYIDA AJANDA BASTIRILACAGI CEVABI SORGUSU  */

SELECT 
SUBSTRING(NAME_,1,1)+'.'+SUBSTRING(SURNAME,1,1)+'.' AS SHORTNAME,
COUNT(*) AS PERSONCOUNT
FROM PERSON
GROUP BY SUBSTRING(NAME_,1,1)+'.'+SUBSTRING(SURNAME,1,1)+'.'
ORDER BY COUNT(*) DESC


/* MAAS ORTALAMASI 5500 TL DEN FAZLA OLAN 
DEPARTMANLARI LISTELEYECEK SORGUYU YAZIN */

SELECT 
D.DEPARTMENT, ROUND(AVG(P.SALARY),0) AS AVGSALARY
FROM DEPARTMENT D
INNER JOIN PERSON P ON P.DEPARTMENTID = D.ID
GROUP BY D.DEPARTMENT
HAVING AVG(P.SALARY) > 5500 

/* DEPARTMANLARIN ORTALAMA KIDEMINI AY OLARAK HESAPLAYACAK 
SORGU YAZIN */

SELECT DEPARTMENT,AVG(WORKINGTIME)
FROM
(
SELECT D.DEPARTMENT,
CASE WHEN OUTDATE IS NOT NULL THEN DATEDIFF(MONTH,INDATE,OUTDATE)
ELSE DATEDIFF(MONTH,INDATE,GETDATE()) 
END AS WORKINGTIME
FROM PERSON P
INNER JOIN DEPARTMENT D ON D.ID=P.DEPARTMENTID
)T GROUP BY DEPARTMENT
ORDER BY DEPARTMENT 


/* HER PERSONELIN ADI,POZISYONU BAGLI OLDUGU BIRIM YONETICISININ ADINI VE POZISYONUNU
GETIREN SORGU */

SELECT
P.NAME_+' '+P.SURNAME AS PERSON,POS.POSITION,
P2.NAME_+' '+P2.SURNAME AS MANAGERNAME,POS2.POSITION AS MANAGERPOSITION

FROM PERSON P
INNER JOIN POSITION POS ON POS.ID = P.POSITIONID
INNER JOIN PERSON P2 ON P.MANAGERID = P2.ID
INNER JOIN POSITION POS2 ON POS2.ID = P2.POSITIONID

WHERE P.NAME_+' '+P.SURNAME IN 
('SELÇUK ALÝKOÇ','SARE ARAZLI','Memet ÇILDIK','Nazife ALAGEYÝK','Zeynep BAKIRÖZÜ')