/* CUSTOMERS TABLOSUNDAN A HARFÝ ÝLE BAÞLAYAN KÝÞÝLER */
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%' 

/* CUSTOMERS TABLOSUNDAN ADI A HARFÝ ÝLE BAÞLAYAN ERKEK MÜÞTERÝLERÝ ÇEK */
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%' AND GENDER = 'E' 

/* 1990 VE 1995 YILLARI ARASINDA DOÐAN MÜÞTERÝLERÝ ÇEKÝNÝZ. 1990 VE 1995 YILLARI DAHÝLDÝR */

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '1990-01-01' AND  '1995-12-31' 

/* ÝSTANBULDA YAÞAYAN KÝÞÝLERÝ JOÝN KULLANARAK GETÝR */

SELECT C.*, CT.CITIES FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID = CT.ID 
WHERE CT.CITIES = 'ÝSTANBUL'   


 /* ÝSTANBULDA YAÞAYAN KÝÞÝLERÝ SUBQUERY KULLANARAK GETÝR  */

 SELECT
 (SELECT CITIES FROM CITIES WHERE ID=C.CITYID),
 * FROM CUSTOMERS C  


 /* HANGÝ ÞEHÝRDE KAÇ MÜÞTERÝ VAR  */

SELECT CT.CITIES,COUNT(C.ID) FROM CUSTOMERS C 
RIGHT JOIN CITIES CT ON CT.ID = C.CITYID
GROUP BY CT.CITIES 


/* 10 DAN FAZLA MÜÞTERÝMÝZ OLAN ÞEHÝRLERÝ MÜÞTERÝ SAYISI ÝLE BÝRLÝKTE MÜÞTERÝ SAYISINA GÖRE
FAZLADAN AZA DOÐRU SIRALA  */

SELECT CT.CITIES, COUNT(C.ID) AS CUSTOMERCOUNT FROM CUSTOMERS C
INNER JOIN CITIES  CT ON CT.ID = C.CITYID
GROUP BY CT.CITIES
HAVING COUNT(C.ID) > 10
ORDER BY CUSTOMERCOUNT DESC 

/* HANGÝ ÞEHÝRDE KAÇ ERKEK, KAÇ KADIN MÜÞTERÝMÝZÝN OLDUÐU BÝLGÝSÝNÝ GETÝR 

SELECT CT.CITIES,C.GENDER,COUNT(C.ID) AS CUSTOMERCOUNT
FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID = C.CITYID
GROUP BY CT.CITIES,C.GENDER
ORDER BY CT.CITIES,C.GENDER  */

SELECT CITIES AS SEHIRADI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID) AS MUSTERISAYISI,
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID AND GENDER = 'E') AS ERKEKSAYISI, 
(SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID=C.ID AND GENDER = 'K') AS KADINSAYISI
FROM CITIES C 







 

